web_application/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { 
    :sessions => "users/sessions", 
    :registrations => "users/registrations", 
    :passwords => "users/passwords", 
    :confirmations => "users/confirmations", 
    :unlocks => "users/unlocks",
    :omniauth_callbacks => "users/omniauth_callbacks"
    } do
      get "/login" => "devise/sessions#new"
      get "/logout" => "devise/sessions#destroy"
      get "/auth/:provider/callback" => "devise/sessions#create"
      get "session/destroy" => "devise/sessions#destroy"
    end
    
    get "users", to: "users#index"
    delete "users/:id", to: "users#destroy"

    get "user_unlock", to: "users#unlock"
  
    post "comments", to: "new_comments#create"
    post "votes", to: "new_votes#create"

    get 'manage_reports/download', to: 'manage_reports#download'
    get 'manage_reports/download_group', to: 'manage_reports#download_group'

    resources :notes
    resources :manage_reports
    resources :new_votes
    resources :new_comments
    resources :rescan_reports
    resources :behavior_reports
    resources :mitre_reports
    resources :groups
    resources :past_reports
    resources :hashes
    resources :urls
    resources :reports
    resources :binaries
    resources :users

  resources :users, only: [:index] do
    member do
      patch :ban
      patch :rescan
      patch :votes
      patch :comments
      patch :behavior
      patch :mitre
      post :unlock
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "reports#index"
end

web_application/app/models/report.rb
class Report < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy    
    has_many :notes, dependent: :destroy

    belongs_to :group, optional: true
    belongs_to :user
end

web_application/app/controllers/reports_controller.rb
require 'uri'
require 'net/http'

class ReportsController < ApplicationController

  before_action :authenticate_user!

  #load_and_authorize_resource

  def index
  end

  def show
    # find report given id
    @report = Report.find(params[:id])
    if @report["group_id"]
      @group = Group.find(@report["group_id"])
    end
  end
  def destroy
    @report = Report.find(params[:id])

    user=User.find(session["warden.user.user.key"][0]).first
    if user.id==@report.user_id || user.has_role?(:admin)
      @report.destroy
      redirect_to past_reports_path, status: :see_other
    else
      redirect_to root_path, notice: "you can't destroy this report"
    end
  end

  def edit
    @report = Report.find(params[:id])
  end
  def update
    @report = Report.find(params[:id])
    @report.update_attribute(:score, params["report"]["score"])
  end
end

web_application/app/helpers/reports_helper.rb
module ReportsHelper
end

web_application/app/views/reports/edit.html.erb
<h1>Reports#edit</h1>

<%= form_for(@report) do |form| %>
  <%= form.label :score, "change score:" %>
  <%= form.number_field :score, in: 1..100 %>
  <%= form.hidden_field :id, value: "#{params["id"]}" %>
  <%= form.submit "Submit" %>
<% end %>

<% if !current_user.has_role?(:not_comments) %>
    <h3>COMMENTS</h3>
        <ul>
        <% @report.comments.each do |comment| %>
            <li>
            <%= comment.body %>
            <%= link_to "[ Delete ]", new_comment_path(comment.id), data: {
                    turbo_method: :delete,
                    } %>
            </li>
        <% end %>
        </ul>
<% end %>

<% if !current_user.has_role?(:not_votes) %>
    <h3>VOTES</h3>
        <ul>
        <% @report.votes.each do |vote| %>
            <li>
            <%= vote.verdict %>
            <%= vote.value %>
            <%= link_to "[ Delete ]", new_vote_path(vote.id), data: {
                    turbo_method: :delete,
                    } %>
            </li>
        <% end %>
        </ul>
<% end %>

<h3>NOTES</h3>
    <ul>
    <% @report.notes.each do |note| %>
        <li>
        <%= note.content %>
        <%= link_to "[ Delete ]", note_path(note.id), data: {
                  turbo_method: :delete,
                } %>
        </li>
    <% end %>
    </ul>

<p id="notice"><%= notice %></p>
<%= link_to "go back", report_path(@report)  %>

<p>Find me in app/views/reports/new.html.erb</p>

web_application/app/views/reports/index.html.erb
<h1>Benvenuto su VirusScanner<br> Reports: </h1>
<ul>
    <li>
        <%= link_to "upload binary", new_binary_path  %>
    </li>
    <li>
        <%= link_to "upload url", new_url_path  %>
    </li>
    <li>
        <%= link_to "search hash", new_hash_path  %>
    </li>
    <li>
        <%= link_to "history", past_reports_path  %>
    </li>
    <li>
        <%= link_to "group report", new_group_path  %>
    </li>
    <li>
        <%= link_to "upload report", new_manage_report_path  %>
    </li>
</ul>
<p>Find me in app/views/reports/index.html.erb</p>

web_application/app/views/reports/show.html.erb
<h1>Reports#show</h1>

<%= link_to "home", reports_path  %>

<%= link_to "download report", "/manage_reports/download?id=#{@report.id}"  %>

<%= link_to "add note", new_note_path(report_id: @report.id)%>

<%= link_to "edit report", edit_report_path(@report.id) %>

<% if @group %>
    <%= link_to "return to group", group_path(@group)  %>
<% end %>

<% if @report.sha256 && !current_user.has_role?(:not_rescan) %>
    <% sha256 = Base64.encode64(@report.sha256)%>
    <%= link_to "rescan report", rescan_report_path(sha256)  %>
<% end %>

<% if @report.sha256 && current_user.has_role?(:admin)%>
    <% sha256 = Base64.encode64(@report.sha256)%>
    <%= link_to "add comment to report", new_new_comment_path(sha: "#{sha256}", report_id: @report.id) %>
    <%= link_to "add vote to report", new_new_vote_path(sha: "#{sha256}", report_id: @report.id) %>
<% end %>

<% if current_user.has_role?(:admin) && @report.url %>
    <% url = Base64.encode64(@report.url)%>
    <%= link_to "add comment to report", new_new_comment_path(url: "#{url}", report_id: @report.id)  %>
    <%= link_to "add vote to report", new_new_vote_path(url: "#{url}", report_id: @report.id)  %>
<% end %>

<% if @report.url && !current_user.has_role?(:not_rescan)%>
    <% url = Base64.encode64(@report.url)%>
    <%= link_to "rescan report", rescan_report_path(url)  %>
<% end %>

<% if @report.sha256 && !current_user.has_role?(:not_mitre)%>
    <%= link_to "mitre report", mitre_report_path(@report.sha256)  %>
<% end %>

<% if @report.sha256 && !current_user.has_role?(:not_behavior)%>
    <%= link_to "behavior report", behavior_report_path(@report.sha256)  %>
<% end %>



<h3>HASH</h3>
<%= @report.sha256 %>
<h3>SCORE</h3>
<%= @report.score %>
<h3>URL</h3>
<%= @report.url %>


<h3>CONTENT</h3>
<%
json_parsed = JSON.parse(@report.content)
begin
    content = json_parsed["data"]["attributes"]["results"]
    url="true"
rescue
    content = json_parsed["data"][0]["attributes"]["last_analysis_results"]
    url="false"
end
%>
<% if url=="true"%>
    <ul>
    <% content.each do |result| %>
        <li>
        <%= result[0]%> : <%= result[1]["category"] %>, <%= result[1]["result"] %>, <%= result[1]["method"] %>
        </li>
    <%end%>
    </ul>
<%else%>
<ul>
    <% content.each do |result| %>
        <li>
        <%= result[0]%> : <%= result[1]["category"] %>, <%= result[1]["result"] %>, <%= result[1]["method"] %>
        </li>
    <%end%>
    </ul>
<% end %>
    
<% if !current_user.has_role?(:not_comments)%>
    <h3>COMMENTS</h3>
    <ul>
    <% @report.comments.each do |comment| %>
        <li>
        <%= comment.body %>
        </li>
    <% end %>
    </ul>
<% end %>

<% if !current_user.has_role?(:not_votes)%>
    <h3>VOTES</h3>
    <ul>
    <% @report.votes.each do |vote| %>
        <li>
        <%= vote.verdict %>
        <%= vote.value %>
        </li>
    <% end %>
    </ul>
<% end %>

<h3>NOTES</h3>
    <ul>
    <% @report.notes.each do |note| %>
        <li>
        <%= note.content %>
        </li>
    <% end %>
    </ul>


<p>Find me in app/views/reports/show.html.erb</p>